MODEL: "optogpt"

PATH: "${OL_DATA_ROOT}"

PATH_TOKENS: "${OL_DATA_ROOT}"
PATH_MATERIALS: "${OL_DATA_ROOT}/materials/"
PATH_TRAIN_0: "${OL_DATA_ROOT}/train/train-0.safetensors"
PATH_TRAIN_1: "${OL_DATA_ROOT}/train/train-1.safetensors"
PATH_TRAIN_2: "${OL_DATA_ROOT}/train/train-2.safetensors"
PATH_TRAIN_3: "${OL_DATA_ROOT}/train/train-3.safetensors"
PATH_TRAIN_4: "${OL_DATA_ROOT}/train/train-4.safetensors"
PATH_TRAIN_5: "${OL_DATA_ROOT}/train/train-5.safetensors"
PATH_TRAIN_6: "${OL_DATA_ROOT}/train/train-6.safetensors"
PATH_TRAIN_7: "${OL_DATA_ROOT}/train/train-7.safetensors"
PATH_TRAIN_8: "${OL_DATA_ROOT}/train/train-8.safetensors"
PATH_TRAIN_9: "${OL_DATA_ROOT}/train/train-9.safetensors"

PATH_TEST: "${OL_DATA_ROOT}/test/test.safetensors"

PATH_RUN: "${OL_DATA_ROOT}/runs/MD1"
PATH_CKPT: "${OL_DATA_ROOT}/checkpoints/optogpt.safetensors"

# --- training / model hyperparameters ---
NOTRAIN: true
NUM_WORKERS: 4
EPOCHS: 1000
NUM_SAMPLES_TRAIN: 10000
NUM_SAMPLES_VALID: 3000
TRAIN_BATCH: 256
VAL_BATCH: 128
STEPS: 500
D_MODEL: 1024
N_BLOCKS: 6
N_HEADS: 8
DROPOUT: 0.0
MAX_GRAD_NORM: 1000

SEED: 3

DB_DOWNLOAD: false
DB_PLOTNK: false

WAVELENGTH_MIN: 300
WAVELENGTH_MAX: 2000
WAVELENGTH_STEPS: 10
# Optionally:
# WAVELENGTHS: [300, 310, 320, ..., 2000]
MAX_SEQ_LEN: 21
INCIDENCE_ANGLE: 0

TEMPERATURE: 0.65
TOP_K: 0
TOP_P: 0.90
MC_SAMPLES: 10
N_TARGETS: 0

VALIDSIM: "TMM_FAST"
TRACK_STEP_MAE: false
ROI_MIN: 300
ROI_MAX: 2000

# Optionall:
# TARGET: "${OL_DATA_ROOT}/targets/<YOUR_TARGET>.json"
# TARGET: "random"

NOISE:
  enabled: false
  sigma_abs: 0.1
  sigma_rel: 0.00
  per_channel: [1.0, 0.0, 1.0]
  wl_min: 1200
  wl_max: 2000
  clip_0_1: false

SMOOTH:
  enabled: false
  method: "gaussian"
  win: 25
  sigma: 1.10

MISMATCH_FILL_ORDER: "R>T>A"

