"""Plot the eight curated four-layer examples generated by OptoLlama's TMM."""

from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt

plt.switch_backend("Agg")


def parse_args() -> argparse.Namespace:
    """Parse command-line options."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, default=Path("data/examples/four_layer_interesting"))
    parser.add_argument("--output", type=Path, default=None, help="Output PNG, SVG, or PDF path.")
    parser.add_argument("--dpi", type=int, default=180)
    return parser.parse_args()


def load_spectra(path: Path) -> dict[int, dict[str, list[float]]]:
    """Load the long-form spectra CSV grouped by sample index."""
    spectra: dict[int, dict[str, list[float]]] = defaultdict(
        lambda: {"wavelength_nm": [], "R": [], "A": [], "T": []}
    )
    with path.open("r", encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle):
            sample = spectra[int(row["sample_index"])]
            for key in ("wavelength_nm", "R", "A", "T"):
                sample[key].append(float(row[key]))
    return dict(spectra)


def main() -> None:
    """Render all eight spectra as a shared-axis panel figure."""
    args = parse_args()
    manifest_path = args.data_dir / "manifest.json"
    spectra_path = args.data_dir / "spectra.csv"
    output_path = args.output or (args.data_dir / "overview.png")
    if not manifest_path.is_file() or not spectra_path.is_file():
        raise FileNotFoundError(f"Expected manifest.json and spectra.csv in {args.data_dir}")

    with manifest_path.open("r", encoding="utf-8") as handle:
        manifest = json.load(handle)
    spectra = load_spectra(spectra_path)
    samples = manifest["samples"]
    if len(samples) != 8 or set(spectra) != set(range(8)):
        raise ValueError("This overview expects the complete eight-sample example dataset.")

    plt.rcParams.update(
        {
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.titleweight": "semibold",
            "font.size": 9,
        }
    )
    figure, axes = plt.subplots(4, 2, figsize=(13, 12), sharex=True, sharey=True, constrained_layout=True)
    colors = {"R": "#3366cc", "A": "#d33f49", "T": "#2a9d5b"}

    for index, (axis, sample) in enumerate(zip(axes.flat, samples, strict=True)):
        curve = spectra[index]
        for channel in ("R", "A", "T"):
            axis.plot(
                curve["wavelength_nm"],
                curve[channel],
                color=colors[channel],
                label=channel,
                linewidth=1.7,
            )
        stack = " / ".join(layer.replace("_", " ") for layer in sample["layers"])
        axis.set_title(f"{index + 1}. {sample['name'].replace('_', ' ')}\n{stack}", fontsize=9.5)
        axis.set_xlim(curve["wavelength_nm"][0], curve["wavelength_nm"][-1])
        axis.set_ylim(-0.02, 1.02)
        axis.set_yticks((0.0, 0.25, 0.5, 0.75, 1.0))
        axis.grid(True, color="#d9d9d9", linewidth=0.6, alpha=0.75)
        if index % 2 == 0:
            axis.set_ylabel("Fraction")
        if index >= 6:
            axis.set_xlabel("Wavelength (nm)")

    handles, labels = axes[0, 0].get_legend_handles_labels()
    figure.legend(handles, labels, loc="outside lower center", ncol=3, frameon=False)
    simulation = manifest["simulation"]
    figure.suptitle(
        "Eight four-layer thin-film examples\n"
        f"Coherent TMM · {simulation['incidence_angle_deg']:g}° incidence · "
        f"{simulation['polarization']}-polarization · air / stack / air",
        fontsize=14,
        weight="bold",
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(output_path, dpi=args.dpi, bbox_inches="tight")
    plt.close(figure)
    print(f"Saved {output_path}")


if __name__ == "__main__":
    main()
